services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    restart: on-failure
  
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - mariadb
      - nginx
  
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception_network
    restart: on-failure

volumes:
  wordpress:
  db:

networks:
  inception_network: